### ISSUE TITLE
please 

### ISSUE THREAD

**Issue by DimonYoing** [Aetheam/Skyblock_Aethteam-inDev-#1]
Create the ID item plugin, if you enter the /ID command, then the block ID is written to the chat.
In plugin.yml add command description

**Comment by royaljacques** [comment]
what could this be used for a skyblock plugin?

**Comment by royaljacques** [comment]
I'll make one as soon as I have time.

**Comment by royaljacques** [comment]
see https://github.com/Aetheam/SimpleIds_AethTeam
